language: android

branches:
  only:
    - master

jdk:
  - oraclejdk7

android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-android-m2repository
    - extra-google-m2repository
    - platform-tools
    - tools

script:
  - ./gradlew build
  - ./gradlew test

sudo: false

cache:
  directories:
    - $HOME/.gradle