# Locale configuration to emulate site.github variable
baseurl: "" # the subpath of your site, e.g. /blog
url: ""
github:
    contributors:
    - {
        avatar_url: 'https://avatars1.githubusercontent.com/u/1009664?v=3&s=460',
        contributions: 50,
        html_url: 'https://github.com/MGaetan89',
        login: MGaetan89
    }
    - {
        avatar_url: 'https://github.com/github.png',
        contributions: 25,
        html_url: 'https://github.com/Octocat',
        login: Octocat
    }
    issues_url: https://github.com/MGaetan89/ShowsRage/issues
    project_title: ShowsRage
    releases_url: https://github.com/MGaetan89/ShowsRage/releases
    repository_url: https://github.com/MGaetan89/ShowsRage
    url: https://MGaetan89.github.io/ShowsRage/
